version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install uv
      - uv venv --system-site-packages .venv
      - . .venv/bin/activate
      - uv pip sync docs/requirements.lock

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
