FROM pytorchlightning/pytorch_lightning

WORKDIR /app

RUN pip install uv

RUN uv venv .venv
ENV PATH="/app/.venv/bin:$PATH"

COPY pyproject.toml requirements.lock ./
RUN uv pip sync requirements.lock

# Install Jupyter
RUN uv pip install jupyterlab

# Expose port for Jupyter
EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]