[project]
name = "hi-notebooks"
version = "0.1.0"
description = "Hybrid Intelligence Knowledge Archival Notebooks"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "seaborn",
]
requires-python = ">=3.11"
